# https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/

modLoader = "lowcodefml"
loaderVersion = "[1,)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

license = "AGPL-3.0"
issueTrackerURL = "https://github.com/"
showAsResourcePack = true

[[mods]]
modId = "vanilla_tweaks_mango_edition"
version = "1.0.0"
displayName = "Vanilla Tweaks - Mango Edition"
description = """a collection of quality-of-life improvements and tweaks for Minecraft, designed to enhance the vanilla gameplay experience without altering the core mechanics."""
logoFile = "pack.png"
# updateJSONURL = ""
credits = "Vanilla Tweaks"
authors = "Vanilla Tweaks Team, MangoJellyPudding"
displayURL = "https://github.com/Mango-Minecraft-Project/Vanilla-Tweaks-Mango-Edition"

[[dependencies.vanilla_tweaks_mango_edition]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.21)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
side = "CLIENT" # BOTH, CLIENT, SERVER. default is BOTH

[[dependencies.vanilla_tweaks_mango_edition]]
modId = "ars_nouveau"
mandatory = false
side = "CLIENT"

[[dependencies.vanilla_tweaks_mango_edition]]
modId = "farmersdelight"
mandatory = false
side = "CLIENT"

[[dependencies.vanilla_tweaks_mango_edition]]
modId = "manors_bounty"
mandatory = false
side = "CLIENT"