# https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/

modLoader = "lowcodefml"
loaderVersion = "[1,)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

license = "AGPL-3.0"
issueTrackerURL = "https://github.com/"
# showAsDataPack = false
# showAsResourcePack = false
# clientSideOnly = false

[[mods]]
modId = ""
version = "0.0.1"
displayName = ""
description = """"""
logoFile = "pack.png"
# updateJSONURL = ""
# credits = ""
authors = ""
# displayURL = "https://github.com/"

[[dependencies.mod_id]]
modId = "minecraft"
mandatory = true
# versionRange = "" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
# ordering = "NONE" # NONE, AFTER, BEFORE. default is NONE
# side = "BOTH" # BOTH, CLIENT, SERVER. default is BOTH